version: "2"
services:
  registry:
    image: registry:2
    environment:
      - REGISTRY_HTTP_SECRET=o43g2kjgn2iuhv2k4jn2f23f290qfghsdg
      - REGISTRY_STORAGE_DELETE_ENABLED=
    volumes:
      - ./registry-data:/var/lib/registry
  ui:
    image: jc21/registry-ui
    environment:
      - NODE_ENV=production
      - REGISTRY_HOST=registry:5000
      - REGISTRY_SSL=
      - REGISTRY_DOMAIN=
      - REGISTRY_STORAGE_DELETE_ENABLED=
    links:
      - registry
    restart: on-failure
  proxy:
    image: jc21/registry-ui-proxy
    ports:
      - 80:80
    depends_on:
      - ui
      - registry
    links:
      - ui
      - registry
    restart: on-failure
